---
title: BESLIF
timezone: America/Sao_Paulo
collections:
  posts:
    title: Home
    output: true
    description: Bem-vindo(a) ao BESLIF!
  investimentos:
    title: Investimentos
    output: true
    description: Aqui você verá os investimentos recomendados.
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
remote_theme: daviddarnes/garth
exclude:
- README.md
plugins:
- jekyll-paginate
- jekyll-remote-theme
paginate: 3
paginate_path: page:num
sass:
  style: compressed
permalink: none
excerpt_separator: "<!-- more -->"
encoding: utf-8
logo: "assets/logo.svg"
description: Viva sua melhor vida
url: https://beslif.github.io
baseurl: 
lang: pt-BR
