---
title: BESLIF
timezone: America/Sao_Paulo
collections:
  posts:
    title: Home
    output: true
    description: Não sabemos se você escaneou um dos QR Codes ou se alguém te indicou esse site, mas uma coisa é certa. Se você deseja potencializar sua vida financeira, está no lugar certo! Bem-vindo ao [BESLIF](https://beslif.github.io/sobre), um projeto de empreendedorismo que busca conciliar a saúde mental à vida financeira, a fim de garantir aos seus usuários a melhor vida possível.
  investimentos:
    title: Investimentos
    output: true
    description: Bem-vindo(a) à página de investimentos. Aqui você pode ver os melhores investimentos a serem feitos.
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
remote_theme: daviddarnes/garth
exclude:
- README.md
plugins:
- jekyll-paginate
- jekyll-remote-theme
paginate: 3
paginate_path: page:num
sass:
  style: compressed
permalink: none
excerpt_separator: "<!-- more -->"
encoding: utf-8
logo: "assets/logo.svg"
description: Viva sua melhor vida
url: https://beslif.github.io
baseurl: 
lang: pt-BR
